server:
  port: 80


spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.237.182:3306/mytest?characterEncoding=utf8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456aas
eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 入驻地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka